before_install:
  #- sudo apt-add-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get update -q
  # Removal of postgresql-9.1-postgis-scripts is needed due to a
  # bug in some upstream package.
  # See http://trac.osgeo.org/ubuntugis/ticket/39
  - sudo apt-get remove --purge -q postgresql-9.1-postgis-scripts 
  - sudo apt-get install -q postgresql-9.1-postgis gdal-bin
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis
  - ./configure

language: node_js
node_js:
  - "0.8"
  - "0.10"
