# We cannot use the postgresql addon with postgis and gdal-bin from the precise packages
# See https://github.com/travis-ci/travis-ci/issues/2683#issuecomment-52709865
#addons:
#  postgresql: "9.3"

before_install:
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq purge postgis* postgresql*
  - sudo rm -Rf /var/lib/postgresql /etc/postgresql
  - sudo apt-add-repository --yes ppa:cartodb/postgresql-9.3
  - sudo apt-add-repository --yes ppa:cartodb/gis
  - sudo apt-get update
  - sudo apt-get install -q postgresql-9.3-postgis-2.1
  - sudo apt-get install -q postgresql-contrib-9.3
  - sudo apt-get install -q postgresql-plpython-9.3
  - sudo apt-get install -q postgis
  - sudo apt-get install -q gdal-bin
  - echo -e "local\tall\tall\ttrust\nhost\tall\tall\t127.0.0.1/32\ttrust\nhost\tall\tall\t::1/128\t
  - sudo service postgresql restart
  - psql -c 'create database template_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d template_postgis
  - ./configure

env:
  - PGUSER=postgres

language: node_js
node_js:
  - "0.8"
  - "0.10"
